## ============================================================
## SCENIC Regulon AUC Integration into Seurat Objects
## Figures: data source for Fig 3A, Fig 3B, Fig S3A, Fig S3B, Fig S3D
## Dataset: GSE138709 (5 tumor + 3 adjacent iCCA samples)
## ============================================================
## Prerequisites:
##   - scRNA1: Seurat object with article cell annotations
##   - int/3.4_regulonAUC.Rds from 08_data_SCENIC_regulon_inference_for_Fig3_FigS3.R
##   - int/4.1_binaryRegulonActivity.Rds, if binary activity is needed
## Output:
##   - auc_mtx: regulon x cell AUC matrix
##   - bin_mtx: regulon x cell binary activity matrix, when available
##   - scRNAauc: scRNA1 with regulon AUC metadata
##   - scRNAbin: scRNA1 with binary regulon metadata, when available
##   - output/scRNAauc.rds and output/scRNAbin.rds
## Notes:
##   - This script is a data source only. Final heatmaps/volcano/density plots
##     are generated by scripts 10, 14, 15, and 17.
## ============================================================

suppressPackageStartupMessages({
  library(Seurat)
})

Sys.setenv(LANGUAGE = "en")
options(stringsAsFactors = FALSE)

if (!exists("scRNA1") || !inherits(scRNA1, "Seurat")) {
  candidates <- c("output/scRNA1_annotated.rds", "output/scRNA1_preprocessed.rds")
  hit <- candidates[file.exists(candidates)][1]
  if (is.na(hit)) {
    stop("scRNA1 was not found in memory and no expected RDS exists in output/.")
  }
  scRNA1 <- readRDS(hit)
}

dir.create("output", showWarnings = FALSE, recursive = TRUE)

sanitize_regulon_names <- function(x) {
  x <- gsub(" \\(", "_", x)
  x <- gsub("\\)", "", x)
  x <- gsub("[^A-Za-z0-9_.-]+", "_", x)
  make.unique(x)
}

extract_auc_matrix <- function(x) {
  if (is.matrix(x) || is.data.frame(x)) {
    return(as.matrix(x))
  }
  if (requireNamespace("SCENIC", quietly = TRUE)) {
    out <- tryCatch(SCENIC::getAUC(x), error = function(e) NULL)
    if (!is.null(out)) return(as.matrix(out))
  }
  out <- tryCatch(x@assays@data@listData$AUC, error = function(e) NULL)
  if (!is.null(out)) return(as.matrix(out))
  stop("Could not extract regulon AUC matrix from the supplied RDS object.")
}

add_regulon_metadata <- function(obj, regulon_by_cell, prefix = NULL) {
  common <- intersect(colnames(obj), colnames(regulon_by_cell))
  if (!length(common)) {
    stop("No overlapping cells between Seurat object and regulon matrix.")
  }

  meta <- matrix(
    NA_real_,
    nrow = ncol(obj),
    ncol = nrow(regulon_by_cell),
    dimnames = list(colnames(obj), rownames(regulon_by_cell))
  )
  meta[common, ] <- t(regulon_by_cell[, common, drop = FALSE])
  meta <- as.data.frame(meta, check.names = FALSE)

  if (!is.null(prefix)) {
    colnames(meta) <- paste0(prefix, colnames(meta))
  }
  AddMetaData(obj, metadata = meta)
}

auc_file <- file.path("int", "3.4_regulonAUC.Rds")
if (!file.exists(auc_file)) {
  cand <- list.files("int", pattern = "^3\\.4_regulonAUC.*\\.Rds$",
                     full.names = TRUE)
  if (!length(cand)) stop("No regulon AUC RDS was found in int/.")
  auc_file <- cand[1]
}

auc_raw <- readRDS(auc_file)
auc_mtx <- extract_auc_matrix(auc_raw)
rownames(auc_mtx) <- sanitize_regulon_names(rownames(auc_mtx))

scRNAauc <- add_regulon_metadata(scRNA1, auc_mtx)
if ("integrated" %in% names(scRNAauc@assays)) {
  scRNAauc@assays$integrated <- NULL
}

saveRDS(scRNAauc, "output/scRNAauc.rds")
saveRDS(scRNAauc, "scRNAauc.rds")

bin_file <- file.path("int", "4.1_binaryRegulonActivity.Rds")
if (file.exists(bin_file)) {
  bin_raw <- readRDS(bin_file)
  bin_mtx <- as.matrix(bin_raw)
  rownames(bin_mtx) <- sanitize_regulon_names(rownames(bin_mtx))
  scRNAbin <- add_regulon_metadata(scRNA1, bin_mtx, prefix = "BIN_")
  if ("integrated" %in% names(scRNAbin@assays)) {
    scRNAbin@assays$integrated <- NULL
  }
  saveRDS(scRNAbin, "output/scRNAbin.rds")
  saveRDS(scRNAbin, "scRNAbin.rds")
} else {
  warning("Binary regulon activity file was not found: ", bin_file)
}

saveRDS(auc_mtx, "output/auc_mtx_regulon_by_cell.rds")
if (exists("bin_mtx")) saveRDS(bin_mtx, "output/bin_mtx_regulon_by_cell.rds")

message("Done: SCENIC AUC metadata integrated.")
message("  scRNAauc metadata columns added: ", nrow(auc_mtx))
message("  Shared cells: ", length(intersect(colnames(scRNA1), colnames(auc_mtx))))
